/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import controllers.Controller;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;

/**
 *
 * @author Favoretti
 */
public class PrincipalFrame extends javax.swing.JFrame {
String arq = null;
    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        ;
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        lblTipo.setVisible(false);
        lblType.setVisible(false);
        lblExtensao.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        txtFinput = new javax.swing.JTextField();
        btnSelect = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxConteudo = new javax.swing.JTextArea();
        btnDijk = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JToggleButton();
        rbTxt = new javax.swing.JRadioButton();
        rbXml = new javax.swing.JRadioButton();
        lblTipo = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblExtensao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jFileChooser2.setApproveButtonText("");
        jFileChooser2.setFileFilter(new Filtro());
        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtFinput.setEditable(false);
        txtFinput.setAutoscrolls(false);
        txtFinput.setMaximumSize(new java.awt.Dimension(6, 20));
        txtFinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinputActionPerformed(evt);
            }
        });

        btnSelect.setText("Selecionar Arquivo");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        jLabel1.setText("Arquivo INPUT:");

        atxConteudo.setColumns(20);
        atxConteudo.setRows(5);
        jScrollPane1.setViewportView(atxConteudo);

        btnDijk.setText("Iniciar Dijkstra");
        btnDijk.setEnabled(false);
        btnDijk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDijkActionPerformed(evt);
            }
        });

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        rbTxt.setText("Arquivo .txt");
        rbTxt.setEnabled(false);
        rbTxt.setFocusPainted(false);
        rbTxt.setFocusable(false);
        rbTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTxtActionPerformed(evt);
            }
        });

        rbXml.setText("Arquivo .xml");
        rbXml.setEnabled(false);
        rbXml.setFocusable(false);

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 0, 0));
        lblTipo.setText("Tipo:");

        lblType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 0, 0));

        lblExtensao.setEnabled(false);
        lblExtensao.setFocusable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo-each.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbTxt)
                                        .addGap(0, 9, Short.MAX_VALUE))
                                    .addComponent(txtFinput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbXml)
                                    .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnSair)
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblExtensao)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(btnDijk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTipo)
                        .addGap(10, 10, 10)
                        .addComponent(lblType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rbTxt)
                            .addComponent(rbXml))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelect))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipo)
                                    .addComponent(lblType))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDijk)
                            .addComponent(btnSair))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblExtensao)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
 // TODO add your handling code here:
        
        int returnVal = jFileChooser2.showOpenDialog(this);
 
        String tipo = null;
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser2.getSelectedFile();
            

            try {
                                
                arq = file.getAbsolutePath();
                txtFinput.setText(arq);
                txtFinput.setSize(6,20);
                atxConteudo.read( new FileReader( file.getAbsolutePath() ), null );
            } catch (Exception e) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
        StringTokenizer values = new StringTokenizer(arq, ".");
        String extencao = null;
        while(values.hasMoreTokens()){
            extencao = values.nextToken();
        }
        if(extencao.equals("txt")){
            rbTxt.setSelected(true);
            rbXml.setSelected(false);
            lblExtensao.setText("txt");
            tipo = controllers.ControllerTipos.verificaTipoTxt(arq);
          }
        if(extencao.equals("xml")){
            rbXml.setSelected(true);
            rbTxt.setSelected(false);
            lblExtensao.setText("xml");
            tipo = controllers.ControllerTipos.verificaTipoXml(arq);
         }
        
        if(tipo.equals("1") || tipo.equals("2") || tipo.equals("3") ){
        lblTipo.setVisible(true);
        lblType.setText(tipo);
        lblType.setVisible(true);
        btnDijk.setEnabled(true);
        }
        else{
        lblType.setText("Arquivo inválido");
        lblType.setVisible(true);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void txtFinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinputActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txtFinputActionPerformed

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
      
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnDijkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDijkActionPerformed
      if(lblExtensao.getText().equals("txt")){
         try {
    			Controller.initializeGraphTXT(arq);
    		} catch (Exception ex) {
    			ex.printStackTrace();
    		}
      }
      else if(lblExtensao.getText().equals("xml")){
         try {
    			Controller.initializeGraphXML(arq);
    		} catch (Exception ex) {
    			ex.printStackTrace();
    		}
      }
      
      this.setVisible(false);
      
        
    }//GEN-LAST:event_btnDijkActionPerformed

    private void rbTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxConteudo;
    private javax.swing.JToggleButton btnDijk;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JToggleButton btnSelect;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExtensao;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton rbTxt;
    private javax.swing.JRadioButton rbXml;
    private javax.swing.JTextField txtFinput;
    // End of variables declaration//GEN-END:variables
}
