package interfaceGrafica;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class VisualGrafo extends javax.swing.JFrame {

    /**
     * Creates new form VisualGrafo
     */
    public VisualGrafo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbVisualTxt = new javax.swing.JRadioButton();
        rbVisualXml = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlVisual = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        rbVisualTxt.setText("Em .txt");
        rbVisualTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVisualTxtActionPerformed(evt);
            }
        });

        rbVisualXml.setText("Em .xml");
        rbVisualXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVisualXmlActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Visualizar Saída:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Segundo Exercício Programa - COO");

        pnlVisual.setAutoscrolls(false);
        jScrollPane2.setViewportView(pnlVisual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rbVisualTxt)
                        .addGap(18, 18, 18)
                        .addComponent(rbVisualXml))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbVisualTxt)
                            .addComponent(rbVisualXml)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbVisualTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVisualTxtActionPerformed
    rbVisualXml.setSelected(false);
        try {   
           pnlVisual.read( new FileReader( "src/saidas/output.txt" ), null );
        } catch (IOException ex) {
            Logger.getLogger(VisualGrafo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbVisualTxtActionPerformed

    private void rbVisualXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVisualXmlActionPerformed
    rbVisualTxt.setSelected(false);
    try {   
            pnlVisual.read( new FileReader( "src/saidas/output.xml" ), null );
            
        } catch (IOException ex) {
            Logger.getLogger(VisualGrafo.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rbVisualXmlActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane pnlVisual;
    private javax.swing.JRadioButton rbVisualTxt;
    private javax.swing.JRadioButton rbVisualXml;
    // End of variables declaration//GEN-END:variables
}