/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Favoretti
 */
public class VisualGeral extends javax.swing.JFrame {
 String tipo = null;
        String tempo = null;
        String conjuntoVertices = null;
    /**
     * Creates new form VisualGrafo
     */
    public VisualGeral() {
        initComponents();
       
        this.setLocationRelativeTo(null);
        
    }
    
    public void Parametros(int type, double temp, int numConjuntoVertices){
     lblTipo.setForeground(Color.red);
     lblQtdVert.setForeground(Color.red);
     lblTempo.setForeground(Color.red);
    
     tipo = Integer.toString(type);
     tempo = Double.toString(temp);
     conjuntoVertices = Integer.toString(numConjuntoVertices);
     lblTipo.setText(tipo);
     lblTempo.setText(tempo);
     
     if(type == 3){
     lblQtd.setText("Quantidade de pares de vertices:");
     lblQtdVert.setText(conjuntoVertices);
     } else if (type == 1){
         lblQtdVert.setText(conjuntoVertices);
         lblQtd.setText("Quantidade vertices testados:");
     
     }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbVisualTxt = new javax.swing.JRadioButton();
        rbVisualXml = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlVisual = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        lblQtdVert = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        rbVisualTxt.setText("Em .txt");
        rbVisualTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVisualTxtActionPerformed(evt);
            }
        });

        rbVisualXml.setText("Em .xml");
        rbVisualXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVisualXmlActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Visualizar Saída:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Segundo Exercício Programa - COO");

        pnlVisual.setAutoscrolls(false);
        jScrollPane2.setViewportView(pnlVisual);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tempo decorrido:");

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblTempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblQtd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblQtdVert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo-each.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQtd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQtdVert))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(81, 81, 81)
                        .addComponent(lblTempo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbVisualTxt)
                        .addGap(18, 18, 18)
                        .addComponent(rbVisualXml)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVisualTxt)
                    .addComponent(rbVisualXml)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblTipo))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblTempo))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtd)
                            .addComponent(lblQtdVert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbVisualTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVisualTxtActionPerformed
    rbVisualXml.setSelected(false);
        try {   
           pnlVisual.read( new FileReader( "src/saidas/output.txt" ), null );
        } catch (IOException ex) {
            Logger.getLogger(VisualGeral.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbVisualTxtActionPerformed

    private void rbVisualXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVisualXmlActionPerformed
    rbVisualTxt.setSelected(false);
    try {   
            pnlVisual.read( new FileReader( "src/saidas/output.xml" ), null );
            
        } catch (IOException ex) {
            Logger.getLogger(VisualGeral.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rbVisualXmlActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblQtdVert;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextPane pnlVisual;
    private javax.swing.JRadioButton rbVisualTxt;
    private javax.swing.JRadioButton rbVisualXml;
    // End of variables declaration//GEN-END:variables
}